name: Xbox
main: TStark\Xbox\Main
version: 1.0.0
api: 5.0.0
author: §bT. Stark
description: §6View the Xbox profile of players who are online or offline
website: §ahttps://mcpetools.surge.sh

commands:
  xboxprofile:
    description: "View player's Xbox profile"
    usage: "/xboxprofile <player: target>"
    permission: "xbox.command.profile"
permissions:
  xbox.command.profile:
    default: true
    description: Allows the user to view Xbox profiles
